version: '3'
services:
  framework-app.test:
    build: .docker
    ports:
      - '80:80'
      - '5173:5173'
    volumes:
      - '.:/var/www/html'
    networks:
      - framework
    depends_on:
      - mariadb
      - mailpit
  mariadb:
    image: 'mariadb:10'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: framework
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - './.docker/dbdata:/var/lib/mysql'
    networks:
      - framework
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - framework
networks:
    framework:
        driver: bridge
volumes:
    db:
        driver: local
